export const AIRBNB_CHECKLIST_ITEMS = [
  { name: "Toilet paper", quantity: 6, alert_threshold: 2 },
  { name: "Paper towels", quantity: 2, alert_threshold: 1 },
  { name: "Hand soap", quantity: 2, alert_threshold: 1 },
  { name: "Shampoo", quantity: 4, alert_threshold: 2 },
  { name: "Conditioner", quantity: 4, alert_threshold: 2 },
  { name: "Body wash", quantity: 2, alert_threshold: 1 },
  { name: "Coffee sachets", quantity: 20, alert_threshold: 8 },
  { name: "Tea bags", quantity: 20, alert_threshold: 8 },
  { name: "Sugar sachets", quantity: 20, alert_threshold: 8 },
  { name: "Cooking oil", quantity: 1, alert_threshold: 1 },
  { name: "Salt & pepper", quantity: 1, alert_threshold: 1 },
  { name: "Dish soap", quantity: 1, alert_threshold: 1 },
  { name: "Sponge", quantity: 2, alert_threshold: 1 },
  { name: "Trash bags", quantity: 10, alert_threshold: 4 },
  { name: "Laundry detergent", quantity: 1, alert_threshold: 1 },
  { name: "Bath towels", quantity: 6, alert_threshold: 3 },
  { name: "Hand towels", quantity: 4, alert_threshold: 2 },
  { name: "Bed sheets (queen)", quantity: 3, alert_threshold: 1 },
  { name: "Pillowcases", quantity: 6, alert_threshold: 3 },
  { name: "Duvet covers", quantity: 2, alert_threshold: 1 },
  { name: "Toilet brush", quantity: 1, alert_threshold: 1 },
  { name: "Air freshener", quantity: 1, alert_threshold: 1 },
  { name: "Light bulbs", quantity: 4, alert_threshold: 2 },
  { name: "Batteries (AA)", quantity: 4, alert_threshold: 2 },
  { name: "First aid kit", quantity: 1, alert_threshold: 1 },
] as const;
